- Le joueur doit utiliser un bateau pour naviguer en mer.
- Le joueur peut acheter des marchandises et les mettres dans un bateau.
- Le joueur peut vendre des marchandises depuis un bateau.
- Des villes supplémentaires
- Des mers supplémentaires
